apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-wordpress-app.fullname" . }}
  labels:
    {{- include "my-wordpress-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-wordpress-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-wordpress-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "your-database-host"
            - name: WORDPRESS_DB_USER
              value: "your-database-user"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-password
            - name: WORDPRESS_DB_NAME
              value: "your-database-name"
